### PR TITLE
Benchmark refactoring

### PR DESCRIPTION
**Pull request by ekuvardin**
So, what I found and try to change.
1. Each benchmark return void but call to mapper.map return not void value. Compiler may optimize execution and thrown away some computation to prevent so bechmark should return value(more info http://hg.openjdk.java.net/code-tools/jmh/file/25d8b2695bac/jmh-samples/src/main/java/org/openjdk/jmh/samples/JMHSample_08_DeadCode.java) or use Blakcholes when multiple values are returned(ex http://hg.openjdk.java.net/code-tools/jmh/file/25d8b2695bac/jmh-samples/src/main/java/org/openjdk/jmh/samples/JMHSample_09_Blackholes.java)
Solved by add returning value
2. Tests by default use implicit` @Setup(Level.Trial)` and all ex. of dozerMapper, orikaMapper, etc will be recreated before each becnhmark running but for example when running Dozer bechmark then all others mapper aren't use during this evaluation. I think it's not correct and compiler is smart enough to detect dead code or unused value and do some optimization that can influence on test(remove unused value on 3-4 iteration following to higner errors amplitude)
Solved by using `@Param`. Can be used separate tests for different mappers.
3. In each test you use OrderFactory.buildOrder() and JMH can inline this code into benchmark in each iteration to prevent so I suggest create new example(may be the same) before each iteration.
Solved by adding 
 `
 @Setup(Level.Iteration)
    public void preInit(){
        order = OrderFactory.buildOrder();
    }
 `
Some notes. Test metric before includes creating example
        `mapper.map(OrderFactory.buildOrder())`
I think we measure mapping, not creating some classes.
But on the other hand it is correct too when mapping takes much bigger time then creating some examples.
4. When I run benchmark with Java 1.8 I get error
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Solved by adding dependency in pom.xml
5. Also add compability starting with Java 1.7
`<javac.target>1.7</javac.target>`
cause I use `swith(String)`. I think it can't be harmful.
6. As you can see Error is increasing but in the range [1.5%-6.8%]
7. I don't change .png file. Cause I think may be you can test on your machine and get another results?

### CODE REVIEW

**Comment by arey** [comment]
Thanks a lot @ekuvardin for all your work.
Here are my comments:
1. I don't see any return method into the unique @Benchmark annotated mapper method. Is it an oversight?
3. Yes, we are testing mapper, not instanciation of input data classes.
4. Addinga  JAXB dependency seems strange because JAXB is included to the JDK. I don't have your NoClassDefFoundError error with my JDK 8. Nevemind, we could keep it.
7. No problem to generate the png file from my laptop.

**Comment by ekuvardin** [comment]
> I don't see any return method into the unique @benchmark annotated mapper method. Is it an oversight.
This is my fault. Add new commit with return statement and new results. Please check.

**Comment by arey** [comment]
Ok thank you. I will merge :)

**Comment by arey** [comment]
I've re-executed 4 times the micro-benchmark with your refactoring.
At each time, the manual mapper stands at the third place behind MapStruct and Selma.
To reach again the first place, I had to refactore the code by removing private methods. It looks like JVM inlining does not work.

**Comment by ekuvardin** [comment]
I think it's depend on Java version. For ex look at the benchmark below. I use version before your changes(with my last commit)
```
    @Benchmark
    public OrderDTO mapper() {
        return mapper.map(order);
    }

    @Benchmark
    @Fork(jvmArgs = "-XX:MaxInlineLevel=1" , value = 1)
    public OrderDTO mapperInline1() {
        return mapper.map(order);
    }

    @Benchmark
    @Fork(jvmArgs = "-XX:MaxInlineLevel=30", value = 1)
    public OrderDTO mapperInline30() {
        return mapper.map(order);
    }
```
Java 9
```
Benchmark                             (type)   Mode  Cnt         Score         Error  Units
MapperBenchmark.mapper          ManualMapper  thrpt    5  22836119,597    962566,334  ops/s
MapperBenchmark.mapperInline1   ManualMapper  thrpt    5  16217539,208   1213129,874  ops/s
MapperBenchmark.mapperInline30  ManualMapper  thrpt    5  23134300,118    153605,090  ops/s
```
Java 8
```
Benchmark                             (type)   Mode  Cnt         Score        Error  Units
MapperBenchmark.mapper          ManualMapper  thrpt    5  19787337,570   327342,438  ops/s
MapperBenchmark.mapperInline1   ManualMapper  thrpt    5  14405671,159   384344,750  ops/s
MapperBenchmark.mapperInline30  ManualMapper  thrpt    5  19882628,202   480282,171  ops/s
```
Mannual mapper gives the best perfomance but look at time difference.
And below examples from all mappers
Java 9. ManualMapper is the winner
```
Benchmark                        (type)   Mode  Cnt         Score        Error Units
MapperBenchmark.mapper      DozerMapper  thrpt    5     52656,088     4613,943 ops/s
MapperBenchmark.mapper    JMapperMapper  thrpt    5  18474621,490   277405,609 ops/s
MapperBenchmark.mapper     ManualMapper  thrpt    5  22794014,743   727533,882 ops/s
MapperBenchmark.mapper  MapStructMapper  thrpt    5  19421365,111   241252,523 ops/s
MapperBenchmark.mapper      ModelMapper  thrpt    5    168342,169     9068,515 ops/s
MapperBenchmark.mapper      OrikaMapper  thrpt    5   2460490,517    57900,912 ops/s
MapperBenchmark.mapper      SelmaMapper  thrpt    5  22219973,850   750782,472 ops/s
```
Java 8. MapStructMapper  is the winner next ManualMapper   and with a liitle bit difference SelmaMapper.
```
Benchmark                        (type)   Mode  Cnt         Score         Error Units
MapperBenchmark.mapper      DozerMapper  thrpt    5     50637,209     10287,767 ops/s
MapperBenchmark.mapper    JMapperMapper  thrpt    5  17691938,614    584067,958 ops/s
MapperBenchmark.mapper     ManualMapper  thrpt    5  19557303,435   1274001,767 ops/s
MapperBenchmark.mapper  MapStructMapper  thrpt    5  20414989,399   1133204,566 ops/s
MapperBenchmark.mapper      ModelMapper  thrpt    5    212719,122      9380,953 ops/s
MapperBenchmark.mapper      OrikaMapper  thrpt    5   3069991,630     73128,310 ops/s
MapperBenchmark.mapper      SelmaMapper  thrpt    5  19509354,669    418391,058 ops/s
```
By the way it's not so bad. You can add more test with inline hint with descriptions. Under the hood mappers doing a lot of things and you can't influence on that.

**Comment by arey** [comment]
Thanks for your bench. I have the same results with Java 9. Thus I've reverted my refactoring and I've published benchmark on Java 9.

**Pull request merged**
